"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-16 08:35:19.081573
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dictionaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("revision", sa.String(length=100), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("entry_count", sa.Integer(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_estimate", sa.Float(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("title_ja", sa.String(length=200), nullable=True),
        sa.Column("region_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("headword", sa.String(length=100), nullable=False),
        sa.Column("reading", sa.String(length=100), nullable=False),
        sa.Column("pos", sa.String(length=40), nullable=True),
        sa.Column("jmdict_id", sa.String(length=20), nullable=True),
        sa.Column("known_status", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("headword", "reading", name="uq_terms_headword_reading"),
    )
    with op.batch_alter_table("terms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_terms_headword"), ["headword"], unique=False)
        batch_op.create_index(batch_op.f("ix_terms_known_status"), ["known_status"], unique=False)

    op.create_table(
        "dict_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dict_id", sa.Integer(), nullable=False),
        sa.Column("ext_id", sa.String(length=40), nullable=False),
        sa.Column("senses_json", sa.Text(), nullable=False),
        sa.Column("pos_json", sa.Text(), nullable=True),
        sa.Column("common", sa.Boolean(), nullable=False),
        sa.Column("is_expression", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["dict_id"], ["dictionaries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dict_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dict_entries_dict_id"), ["dict_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dict_entries_ext_id"), ["ext_id"], unique=False)

    op.create_table(
        "senses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("gloss_zh", sa.Text(), nullable=True),
        sa.Column("gloss_en", sa.Text(), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["term_id"], ["terms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("senses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_senses_term_id"), ["term_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("text_source", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("stats_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dict_forms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("common", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["dict_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dict_forms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dict_forms_entry_id"), ["entry_id"], unique=False)
        batch_op.create_index("ix_dict_forms_text_kind", ["text", "kind"], unique=False)

    op.create_table(
        "lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("text_hash", sa.String(length=40), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("screenshot_path", sa.String(length=300), nullable=True),
        sa.Column("audio_path", sa.String(length=300), nullable=True),
        sa.Column("position_json", sa.Text(), nullable=True),
        sa.Column("speaker", sa.String(length=100), nullable=True),
        sa.Column("translation_zh", sa.Text(), nullable=True),
        sa.Column("tokens_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lines_captured_at"), ["captured_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_lines_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_lines_text_hash"), ["text_hash"], unique=False)

    op.create_table(
        "encounters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=True),
        sa.Column("surface", sa.String(length=100), nullable=False),
        sa.Column("span_start", sa.Integer(), nullable=False),
        sa.Column("span_end", sa.Integer(), nullable=False),
        sa.Column("contraction_of", sa.String(length=100), nullable=True),
        sa.Column("ai_explanation_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["line_id"], ["lines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sense_id"], ["senses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["term_id"], ["terms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("encounters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_encounters_line_id"), ["line_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_encounters_term_id"), ["term_id"], unique=False)

    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("card_type", sa.String(length=16), nullable=False),
        sa.Column("primary_encounter_id", sa.Integer(), nullable=True),
        sa.Column("review_owner", sa.String(length=16), nullable=False),
        sa.Column("suspended", sa.Boolean(), nullable=False),
        sa.Column("fsrs_state", sa.Integer(), nullable=False),
        sa.Column("fsrs_step", sa.Integer(), nullable=True),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("due", sa.DateTime(), nullable=True),
        sa.Column("last_review", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["primary_encounter_id"], ["encounters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["term_id"], ["terms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("term_id", "card_type", name="uq_cards_term_type"),
    )
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cards_due"), ["due"], unique=False)
        batch_op.create_index(batch_op.f("ix_cards_review_owner"), ["review_owner"], unique=False)
        batch_op.create_index(batch_op.f("ix_cards_term_id"), ["term_id"], unique=False)

    op.create_table(
        "review_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("device_id", sa.String(length=64), nullable=True),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_logs_card_id"), ["card_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_logs_mode"), ["mode"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_logs_mode"))
        batch_op.drop_index(batch_op.f("ix_review_logs_card_id"))

    op.drop_table("review_logs")
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cards_term_id"))
        batch_op.drop_index(batch_op.f("ix_cards_review_owner"))
        batch_op.drop_index(batch_op.f("ix_cards_due"))

    op.drop_table("cards")
    with op.batch_alter_table("encounters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_encounters_term_id"))
        batch_op.drop_index(batch_op.f("ix_encounters_line_id"))

    op.drop_table("encounters")
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lines_text_hash"))
        batch_op.drop_index(batch_op.f("ix_lines_status"))
        batch_op.drop_index(batch_op.f("ix_lines_captured_at"))

    op.drop_table("lines")
    with op.batch_alter_table("dict_forms", schema=None) as batch_op:
        batch_op.drop_index("ix_dict_forms_text_kind")
        batch_op.drop_index(batch_op.f("ix_dict_forms_entry_id"))

    op.drop_table("dict_forms")
    op.drop_table("sessions")
    with op.batch_alter_table("senses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_senses_term_id"))

    op.drop_table("senses")
    with op.batch_alter_table("dict_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dict_entries_ext_id"))
        batch_op.drop_index(batch_op.f("ix_dict_entries_dict_id"))

    op.drop_table("dict_entries")
    with op.batch_alter_table("terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_terms_known_status"))
        batch_op.drop_index(batch_op.f("ix_terms_headword"))

    op.drop_table("terms")
    op.drop_table("sources")
    op.drop_table("settings")
    op.drop_table("llm_calls")
    op.drop_table("dictionaries")
    op.drop_table("devices")
    # ### end Alembic commands ###
