"""cache line unknown count

Revision ID: 0f65b6e861c2
Revises: 85ff227868ef
Create Date: 2026-09-16 23:38:57.840396
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0f65b6e861c2"
down_revision = "4eb2c514e6aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("unknown_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_column("unknown_count")

    # ### end Alembic commands ###
