"""add content locator and ord to lines

Revision ID: 2ba1d1f1e6e1
Revises: 8086168861c3
Create Date: 2026-09-17 00:30:55.400774
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "2ba1d1f1e6e1"
down_revision = "8086168861c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locator_json", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ord", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_lines_ord"), ["ord"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lines_ord"))
        batch_op.drop_column("ord")
        batch_op.drop_column("locator_json")

    # ### end Alembic commands ###
