"""add term pitches

Revision ID: 4eb2c514e6aa
Revises: 85ff227868ef
Create Date: 2026-09-16 23:34:55.683829
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "4eb2c514e6aa"
down_revision = "85ff227868ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "term_pitches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("headword", sa.String(length=200), nullable=False),
        sa.Column("reading", sa.String(length=200), nullable=False),
        sa.Column("accent", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("headword", "reading", "accent", name="uq_term_pitches"),
    )
    with op.batch_alter_table("term_pitches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_term_pitches_headword"), ["headword"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("term_pitches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_term_pitches_headword"))

    op.drop_table("term_pitches")
    # ### end Alembic commands ###
