"""add the kanji table

Revision ID: 57834980b704
Revises: 5f7a9d2c41b8
Create Date: 2026-09-17 02:11:06.406296
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "57834980b704"
down_revision = "5f7a9d2c41b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kanji",
        sa.Column("character", sa.String(length=4), nullable=False),
        sa.Column("on_readings_json", sa.Text(), nullable=False),
        sa.Column("kun_readings_json", sa.Text(), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("jlpt", sa.Integer(), nullable=True),
        sa.Column("stroke_count", sa.Integer(), nullable=True),
        sa.Column("frequency", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("character"),
    )
    with op.batch_alter_table("kanji", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kanji_grade"), ["grade"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kanji", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kanji_grade"))

    op.drop_table("kanji")
    # ### end Alembic commands ###
