"""add subtitle timings to lines

Revision ID: 6d0f65238299
Revises: 0001
Create Date: 2026-09-16 22:16:23.936425
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "6d0f65238299"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start_ms", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("end_ms", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_column("end_ms")
        batch_op.drop_column("start_ms")

    # ### end Alembic commands ###
