"""add term frequencies

Revision ID: 858dd6d115b5
Revises: 6d0f65238299
Create Date: 2026-09-16 23:14:58.321553
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "858dd6d115b5"
down_revision = "6d0f65238299"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "term_frequencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dict_id", sa.Integer(), nullable=False),
        sa.Column("headword", sa.String(length=200), nullable=False),
        sa.Column("reading", sa.String(length=200), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dict_id"], ["dictionaries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dict_id", "headword", "reading", name="uq_term_frequencies"),
    )
    with op.batch_alter_table("term_frequencies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_term_frequencies_dict_id"), ["dict_id"], unique=False)
        batch_op.create_index("ix_term_frequencies_headword", ["headword"], unique=False)
        batch_op.create_index(
            "ix_term_frequencies_headword_reading", ["headword", "reading"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("term_frequencies", schema=None) as batch_op:
        batch_op.drop_index("ix_term_frequencies_headword_reading")
        batch_op.drop_index("ix_term_frequencies_headword")
        batch_op.drop_index(batch_op.f("ix_term_frequencies_dict_id"))

    op.drop_table("term_frequencies")
    # ### end Alembic commands ###
