"""add dictionary attribution columns

Revision ID: 85ff227868ef
Revises: 6d0f65238299
Create Date: 2026-09-16 23:20:40.787768
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "85ff227868ef"
down_revision = "6d0f65238299"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dictionaries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("author", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("attribution", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dictionaries", schema=None) as batch_op:
        batch_op.drop_column("attribution")
        batch_op.drop_column("author")

    # ### end Alembic commands ###
