"""add overlay position to sources

Revision ID: a438c108f90c
Revises: c1a4f2e83d90
Create Date: 2026-09-19 18:33:55.641789
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "a438c108f90c"
down_revision = "c1a4f2e83d90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.add_column(sa.Column("overlay_position_json", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_column("overlay_position_json")

    # ### end Alembic commands ###
